[project]
name = "stainx"
version = "0.1.0"
description = "GPU-accelerated stain normalization"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "torch>=2.0.0",
]
authors = [
    { name = "Yimin Zheng", email = "yzheng@cemm.oeaw.ac.at"}
]
classifier = [
    "Environment :: GPU :: NVIDIA CUDA",
    "Intended Audience :: Developers",
    "Intended Audience :: Healthcare Industry",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development",

]

[tool.uv.workspace]
members = ["packages/stainx-cuda", "packages/stainx-mkl"]

[tool.uv.sources]
stainx-cuda = { workspace = true }
stainx-mkl = { workspace = true }

[dependency-groups]
dev = [
    "ipykernel>=7.0.1",
    "mkdocs>=1.6.1",
    "taskipy>=1.14.1",
]
